/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gol;


import gol.ui.GameFrame;

import java.util.ArrayList;

public class GameOfLife {


    public static boolean isRunning=false;

    public static ArrayList<Rule> rules = new ArrayList<>();

    public static Game game;
    public static GameFrame gameFrame;

    public static void main(String[] args) {
        initRules();

        game = new Game(Vars.defaultWidth, Vars.defaultHeight);
        game.setRule(rules.get(0));
        game.restart(Vars.defaultRatio);

        gameFrame = new GameFrame();
        gameFrame.setVisible(true);

        MainThread.getInstance().start();

    }
    public static void pause(){
        isRunning=false;
        gameFrame.update();
    }
    public static void resume(){
        isRunning=true;
        gameFrame.update();
    }

    private static void initRules() {
        rules.add(new NormalRule("life", "23/3"));
        rules.add(new NormalRule("High Life", "23/36"));
        rules.add(new NormalRule("Sponge cells", "01234567/456"));
        rules.add(new NormalRule("Drills", "24567/3"));
        rules.add(new NormalRule("Condensation", "125678/367"));
        rules.add(new NormalRule("Custom", " / "));
    }

}
