package gol.ui;

import gol.*;

import javax.swing.border.TitledBorder;
import java.awt.*;

/**
 *most of this is auto generated by Netbeans IDE  
 */
public class SettingDialog extends javax.swing.JFrame {
private final NormalRule customRule;
    public SettingDialog() {
        initComponents();
        for (Rule rule : GameOfLife.rules) {
            rulesComboBox.addItem(rule);
        }
        Board board=GameOfLife.game.getBoard();
        edged.setSelected(board.isEdged());
        heightTXT.setText(String.valueOf(board.getHeight()));
        widthTXT.setText(String.valueOf(board.getWidth()));
        updateCheckBox();
        customRule=new NormalRule("custom", "23/3");
    }

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel rulePanel = new javax.swing.JPanel();
        javax.swing.JPanel SRPanel = new javax.swing.JPanel();
        s0 = new javax.swing.JCheckBox();
        s1 = new javax.swing.JCheckBox();
        s2 = new javax.swing.JCheckBox();
        s6 = new javax.swing.JCheckBox();
        s3 = new javax.swing.JCheckBox();
        s5 = new javax.swing.JCheckBox();
        s7 = new javax.swing.JCheckBox();
        s4 = new javax.swing.JCheckBox();
        s8 = new javax.swing.JCheckBox();
        // Variables declaration - do not modify//GEN-BEGIN:variables
        javax.swing.JPanel CRPanel = new javax.swing.JPanel();
        c1 = new javax.swing.JCheckBox();
        c2 = new javax.swing.JCheckBox();
        c3 = new javax.swing.JCheckBox();
        c7 = new javax.swing.JCheckBox();
        c4 = new javax.swing.JCheckBox();
        c6 = new javax.swing.JCheckBox();
        c8 = new javax.swing.JCheckBox();
        c5 = new javax.swing.JCheckBox();
        c0 = new javax.swing.JCheckBox();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        rulesComboBox = new javax.swing.JComboBox<>();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JButton setRuleBTN = new javax.swing.JButton();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel12 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel lh = new javax.swing.JLabel();
        edged = new javax.swing.JCheckBox();
        widthTXT = new javax.swing.JTextField();
        heightTXT = new javax.swing.JTextField();

        setTitle("setting");

        rulePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(
                null,
                "Rule",
                TitledBorder.DEFAULT_JUSTIFICATION,
                TitledBorder.DEFAULT_POSITION,
                new java.awt.Font("Tahoma", Font.PLAIN, 12))); // NOI18N

        SRPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        s0.addActionListener(this::survivalRuleChanged);

        s2.addActionListener(this::survivalRuleChanged);

        s6.addActionListener(this::survivalRuleChanged);

        s7.addActionListener(this::survivalRuleChanged);

        s4.addActionListener(this::survivalRuleChanged);

        s8.addActionListener(this::survivalRuleChanged);

        javax.swing.GroupLayout SRPanelLayout = new javax.swing.GroupLayout(SRPanel);
        SRPanel.setLayout(SRPanelLayout);
        SRPanelLayout.setHorizontalGroup(
            SRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(s0)
                .addGap(18, 18, 18)
                .addComponent(s1)
                .addGap(18, 18, 18)
                .addComponent(s2)
                .addGap(20, 20, 20)
                .addComponent(s3)
                .addGap(18, 18, 18)
                .addComponent(s4)
                .addGap(18, 18, 18)
                .addComponent(s5)
                .addGap(18, 18, 18)
                .addComponent(s6)
                .addGap(18, 18, 18)
                .addComponent(s7)
                .addGap(18, 18, 18)
                .addComponent(s8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SRPanelLayout.setVerticalGroup(
            SRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SRPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(SRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s5)
                    .addComponent(s8)
                    .addComponent(s4)
                    .addComponent(s7)
                    .addComponent(s3)
                    .addComponent(s6)
                    .addComponent(s2)
                    .addComponent(s1)
                    .addComponent(s0))
                .addContainerGap())
        );

        CRPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        c1.addActionListener(this::survivalRuleChanged);

        c2.addActionListener(this::survivalRuleChanged);

        c3.addActionListener(this::survivalRuleChanged);

        c7.addActionListener(this::survivalRuleChanged);

        c4.addActionListener(this::survivalRuleChanged);

        c6.addActionListener(this::survivalRuleChanged);

        c8.addActionListener(this::survivalRuleChanged);

        c5.addActionListener(this::survivalRuleChanged);

        c0.addActionListener(this::survivalRuleChanged);

        javax.swing.GroupLayout CRPanelLayout = new javax.swing.GroupLayout(CRPanel);
        CRPanel.setLayout(CRPanelLayout);
        CRPanelLayout.setHorizontalGroup(
            CRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CRPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(c0)
                .addGap(18, 18, 18)
                .addComponent(c1)
                .addGap(18, 18, 18)
                .addComponent(c2)
                .addGap(18, 18, 18)
                .addComponent(c3)
                .addGap(20, 20, 20)
                .addComponent(c4)
                .addGap(18, 18, 18)
                .addComponent(c5)
                .addGap(18, 18, 18)
                .addComponent(c6)
                .addGap(18, 18, 18)
                .addComponent(c7)
                .addGap(18, 18, 18)
                .addComponent(c8)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CRPanelLayout.setVerticalGroup(
            CRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CRPanelLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(CRPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c0)
                    .addComponent(c6)
                    .addComponent(c5)
                    .addComponent(c8)
                    .addComponent(c4)
                    .addComponent(c7)
                    .addComponent(c3)
                    .addComponent(c2)
                    .addComponent(c1))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Nirmala UI Semilight", Font.PLAIN, 14)); // NOI18N
        jLabel1.setText("Ceation rule");

        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", Font.PLAIN, 14)); // NOI18N
        jLabel3.setText("Survival rule");

        setRuleBTN.setText("Set Rule");
        setRuleBTN.addActionListener(evt -> setRuleBTNActionPerformed(evt));

        jLabel4.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel4.setText("0");

        jLabel5.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel5.setText("Font.BOLD");

        jLabel6.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel6.setText("2");

        jLabel7.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel7.setText("3");

        jLabel8.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel8.setText("4");

        jLabel9.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel9.setText("5");

        jLabel10.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel10.setText("6");

        jLabel11.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel11.setText("7");

        jLabel12.setFont(new java.awt.Font("Tahoma", Font.BOLD, 14)); // NOI18N
        jLabel12.setText("8");

        javax.swing.GroupLayout rulePanelLayout = new javax.swing.GroupLayout(rulePanel);
        rulePanel.setLayout(rulePanelLayout);
        rulePanelLayout.setHorizontalGroup(
            rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rulePanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rulePanelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rulePanelLayout.createSequentialGroup()
                        .addComponent(setRuleBTN)
                        .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(rulePanelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(jLabel6))
                            .addGroup(rulePanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rulesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(21, 21, 21)
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel8)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel9)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel10)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel11)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel12)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rulePanelLayout.setVerticalGroup(
            rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rulePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rulesComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(setRuleBTN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SRPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rulePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CRPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        jLabel2.setText("width:");

        lh.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 14)); // NOI18N
        lh.setText("height:");

        edged.setFont(new java.awt.Font("Tahoma", Font.PLAIN, 12)); // NOI18N
        edged.setText("edged");
        edged.addActionListener(this::edgedActionPerformed);

        widthTXT.addActionListener(this::widthTXTActionPerformed);

        heightTXT.addActionListener(this::heightTXTActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(heightTXT, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                            .addComponent(widthTXT))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(edged))
                    .addComponent(rulePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edged)
                    .addComponent(widthTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lh)
                    .addComponent(heightTXT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rulePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void setRuleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setRuleBTNActionPerformed
        GameOfLife.game.setRule((Rule) rulesComboBox.getSelectedItem());
        updateCheckBox();
    }//GEN-LAST:event_setRuleBTNActionPerformed

    private void survivalRuleChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_survivalRuleChanged
        if (!(GameOfLife.game.getRule() instanceof NormalRule)) {
            return;
        }
      //  GameOfLife.game.setRule(GameOfLife.rules.get(GameOfLife.rules.size() - 1));
      //  rulesComboBox.setSelectedIndex((GameOfLife.rules.size() - 1));

        customRule.setSurvivalRule(0, s0.isSelected()) ;
        customRule.setSurvivalRule(1,s1.isSelected())  ;
        customRule.setSurvivalRule(2,s2.isSelected());
        customRule.setSurvivalRule(3,s3.isSelected());
        customRule.setSurvivalRule(4,s4.isSelected());
        customRule.setSurvivalRule(5,s5.isSelected());
        customRule.setSurvivalRule(6,s6.isSelected());
        customRule.setSurvivalRule(7,s7.isSelected());
        customRule.setSurvivalRule(8,s8.isSelected());
        customRule.setCreateRule(0,c0.isSelected());
        customRule.setCreateRule(1,c1.isSelected());
        customRule.setCreateRule(2,c2.isSelected());
        customRule.setCreateRule(3,c3.isSelected());
        customRule.setCreateRule(4,c4.isSelected());
        customRule.setCreateRule(5,c5.isSelected());
        customRule.setCreateRule(6,c6.isSelected());
        customRule.setCreateRule(7,c7.isSelected());
        customRule.setCreateRule(8,c8.isSelected());
        GameOfLife.game.setRule(customRule);
        System.out.println(GameOfLife.game.getRule());
    }//GEN-LAST:event_survivalRuleChanged

    private void edgedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edgedActionPerformed
        GameOfLife.game.getBoard().setEdged(edged.isSelected());
    }//GEN-LAST:event_edgedActionPerformed

    private void widthTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTXTActionPerformed
        try {
            int n = Integer.parseInt(widthTXT.getText());
            if (n >= Vars.MinWidth && n <= Vars.MaxWidth && n != GameOfLife.game.getBoard().getWidth()) {
                Board board = new Board(n, GameOfLife.game.getBoard().getHeight());
                GameOfLife.game.setBoard(board);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        GameOfLife.gameFrame.update();
    }//GEN-LAST:event_widthTXTActionPerformed

    private void heightTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTXTActionPerformed
        try {
            int newValue = Integer.parseInt(heightTXT.getText());
            Board board=GameOfLife.game.getBoard();
            if (newValue >= Vars.MinHeight && newValue <= Vars.MaxHeight && newValue != board.getHeight()) {
                Board newBoard = new Board( board.getWidth(),newValue);
                GameOfLife.game.setBoard(newBoard);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        GameOfLife.gameFrame.update();
    }//GEN-LAST:event_heightTXTActionPerformed
    public void updateCheckBox() {
        if (GameOfLife.game.getRule() instanceof NormalRule normalRule) {
            s0.setSelected(normalRule.getSurvivalRule()[0]);
            s1.setSelected(normalRule.getSurvivalRule()[1]);
            s2.setSelected(normalRule.getSurvivalRule()[2]);
            s3.setSelected(normalRule.getSurvivalRule()[3]);
            s4.setSelected(normalRule.getSurvivalRule()[4]);
            s5.setSelected(normalRule.getSurvivalRule()[5]);
            s6.setSelected(normalRule.getSurvivalRule()[6]);
            s7.setSelected(normalRule.getSurvivalRule()[7]);
            s8.setSelected(normalRule.getSurvivalRule()[8]);
            c0.setSelected(normalRule.getCreateRule()[0]);
            c1.setSelected(normalRule.getCreateRule()[1]);
            c2.setSelected(normalRule.getCreateRule()[2]);
            c3.setSelected(normalRule.getCreateRule()[3]);
            c4.setSelected(normalRule.getCreateRule()[4]);
            c5.setSelected(normalRule.getCreateRule()[5]);
            c6.setSelected(normalRule.getCreateRule()[6]);
            c7.setSelected(normalRule.getCreateRule()[7]);
            c8.setSelected(normalRule.getCreateRule()[8]);
        }

    }

    private javax.swing.JCheckBox c0;
    private javax.swing.JCheckBox c1;
    private javax.swing.JCheckBox c2;
    private javax.swing.JCheckBox c3;
    private javax.swing.JCheckBox c4;
    private javax.swing.JCheckBox c5;
    private javax.swing.JCheckBox c6;
    private javax.swing.JCheckBox c7;
    private javax.swing.JCheckBox c8;
    private javax.swing.JCheckBox edged;
    private javax.swing.JTextField heightTXT;
    private javax.swing.JComboBox<Rule> rulesComboBox;
    private javax.swing.JCheckBox s0;
    private javax.swing.JCheckBox s1;
    private javax.swing.JCheckBox s2;
    private javax.swing.JCheckBox s3;
    private javax.swing.JCheckBox s4;
    private javax.swing.JCheckBox s5;
    private javax.swing.JCheckBox s6;
    private javax.swing.JCheckBox s7;
    private javax.swing.JCheckBox s8;
    private javax.swing.JTextField widthTXT;
    // End of variables declaration//GEN-END:variables
}
